### ISSUE TITLE
It is backwards for me.

### ISSUE THREAD

**Issue by davefl67** [alberttheprince/popcornrp_black_money_shop#1]
When I use your example code in your README, it offers me one black_money for 5 goldchains. What do I have wrong?

**Comment by alberttheprince** [comment]
This needs to be insured after ox_inventory. If you reset ox_inventory at any point this will not work and needs to be reinsured.

The 1 black_money simply exists so that this resource can detect this is happening, and give you the appropriate amount you set.

**Comment by davefl67** [comment]
That did it. I was restarting `ox_inventory` when I set up the location of the fence. I failed to restart your excellent resource.
