### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by davefl67** [alberttheprince/popcornrp_black_money_shop#2]
- Fence spawns at random locations from a table.
- Fence buys and sells random items from a table.
- Fence can offer to pay in clean money for a much lower payout.

This would make it more challenging to sell items to the fence, plus give options to interact with players.

**Comment by alberttheprince** [comment]
Good ideas, however, I won't be adding additional features to this resource for the foreseeable future. If you do add these, feel free to do a PR, fork it, or re-release it yourself. You're totally free to do whatever you want with this 👍

**Comment by davefl67** [comment]
Cool. Thanks.
