### ISSUE TITLE
improve code

### ISSUE THREAD

**Issue by 137ElPro** [alberttheprince/popcornrp_black_money_shop#3]
local hookId = exports.ox_inventory:registerHook('buyItem', function(payload)
    if payload.metadata.sell then
        SetTimeout(100, function()
            local currencyPrice = payload.metadata.currencyPrice or 1
            exports.ox_inventory:RemoveItem(payload.source, payload.currency, payload.totalPrice)
            exports.ox_inventory:AddItem(payload.source, payload.itemName, currencyPrice*payload.count)
        end)
        return false
    end
end,
{
    print = false,
})
{ name = 'black_money', price = 1, currency = 'panties', metadata = { sell = true, currencyPrice = 250, description = 'vendes: x1 pantie recives 250$-' }},

**Comment by alberttheprince** [comment]
Please make a PR

**Comment by alberttheprince** [comment]
No PR or response
